version: "3.7"
services:
  backend:
    container_name: vstay-api
    environment:
      - NODE_ENV=development
    command: nodemon src/index.js
    ports:
      - 4000:4000
    volumes:
      - ".:/app"
  mongo:
    ports:
      - 27017:27017
  elasticsearch:
    ports:
      - 9200:9200
  kibana:
    ports:
      - 5601:5601
