version: "3.7"
services:
  backend:
    environment:
      - NODE_ENV=production
      - DB_URI=mongodb://mongo:27017/v-stay-db
      - DB_HOST=mongo
      - DB_PORT=27017
    container_name: vstay_api_prod
    image: vstay/api
    command: node src/index.js
    expose:
      - 4000
    volumes:
      - ".:/app"
  mongo:
    expose:
      - 27017
  # elasticsearch:
  #   environment:
  #     - node.name=elasticsearch
  #     - cluster.name=datasearch
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - cluster.initial_master_nodes=elasticsearch
  #     - VIRTUAL_HOST=elastic.vstay.com
  #     - LETSENCRYPT_HOST=elastic.vstay.com
  #     - LETSENCRYPT_EMAIL=tmduc0908@gmail.com
  #   expose:
  #     - 9200
  # kibana:
  #   environment:
  #     - VIRTUAL_HOST=kibana.vstay.com
  #     - LETSENCRYPT_HOST=kibana.vstay.com
  #     - LETSENCRYPT_EMAIL=tmduc0908@gmail.com
  #   expose:
  #     - 5601
networks:
  default:
    external:
      name: nginx-proxy
