version: "3.7"
services:
  backend:
    container_name: vstay-api
    ports:
      - "4000:4000"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - DB_URI=mongodb://mongo:27017/vstay-db
      - DB_HOST=mongo
      - DB_PORT=27017
    restart: always
    links:
      - mongo
  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    container_name: vstay-db
    restart: always
    volumes:
      - "./data/mongo:/data/db"
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
    command: mongod
