# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  # pull_request:
  # branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@master

      - name: Before script
        run: |
          docker build --build-arg NODE_ENV=production -t vstay/api .
          docker save -o vstay-api.tar vstay/api
          zip vstay-api.zip vstay-api.tar
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VSTAY_API_HOST }}
          username: ${{ secrets.VSTAY_API_USER }}
          password: ${{ secrets.VSTAY_API_PASSWORD }}
          port: ${{ secrets.VSTAY_API_PORT }}
          script: |
            scp -P ${{ secrets.VSTAY_API_PORT }} vstay-api.zip ${{ secrets.VSTAY_API_USER }}@${{ secrets.VSTAY_API_HOST }}:${{ secrets.VSTAY_API_WORKDIR }}/api
